### ISSUE TITLE
cloneNode API needed by Aurelia (vNext)

### ISSUE THREAD

**Issue by fkleuver** [ampproject/worker-dom#167]
First of all I would like to say excellent work on what has been accomplished so far. This looks really promising!

We would love to get Aurelia vNext working in worker-dom. The initial attempt to do so can be found [here](https://github.com/fkleuver/worker-dom).

So far it seems the `cloneNode` API is missing. Is there any plan or work-in-progress to add this API?

**Comment by kristoferbaxter** [comment]
Looks like we missed this functionality, will address.

**Comment by EisenbergEffect** [comment]
@kristoferbaxter Great to here! We'll keep providing you all feedback as we work to get Aurelia up and running. Let us know if you need anything from us.

**Comment by kristoferbaxter** [comment]
#169 Adds `Node.cloneNode` by making `Node` have an abstract method `cloneNode(boolean)` and is implemented by all non-abstract classes extending `Node`.

**Comment by fkleuver** [comment]
Nice, thanks for the prompt follow-up! I've tested against your `clone` branch and `cloneNode` is working so far.

The next thing our compiler ran into is `Text#wholeText` missing. We use this to get the `textContent` of a `Text` node and all its sibling `Text` nodes.

Also, `.innerHTML` doesn't appear to have a setter yet but that's already addressed in other issues and it's not a hard blocker for us, so we'll wait for that to settle. Is there any other DOM parsing API exposed or is manually constructing the DOM the only flavor for now?

**Comment by davismj** [comment]
@fkleuver probably should open a new issue

**Comment by fkleuver** [comment]
Maybe you're right. I just noticed some other aggregate issues as well. What's easier for you guys? @kristoferbaxter

**Comment by kristoferbaxter** [comment]
I'm fine with either approach, perhaps let's convert this issue over to a list of the features required to gain support for Aurelia.

**Comment by fkleuver** [comment]
Alright. I'll let this comment be a live checklist.

### Required APIs
- [x] `Node#cloneNode`
- [ ] `Text#wholeText`
- [ ] `Element#innerHTML`

**Comment by kristoferbaxter** [comment]
Started work on `DocumentFragment`. #178.

**Comment by fkleuver** [comment]
Superb, thanks for the update. Let us know if you need something tested or any other help/feedback :)

**Comment by EisenbergEffect** [comment]
Woohoo! @kristoferbaxter Thanks for being so engaged with us and considering our use cases. We're excited about getting Aurelia vNext up and running in a worker and will continue to test and provide feedback along the way.

**Comment by fkleuver** [comment]
@kristoferbaxter Some early feedback: I just tried your `document-fragment` branch and it got things a little further. `createDocumentFragment` works, appending children to it seems to work as well. However it breaks when it tries to materialize the nodes:

```
nodes.js:69 Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('#document-fragment') is not a valid name.
    at createNode (http://localhost:3001/dist/index.mjs:114:85)
    at nodes.forEach.node (http://localhost:3001/dist/index.mjs:700:25)
    at Array.forEach (<anonymous>)
    at mutate (http://localhost:3001/dist/index.mjs:700:9)
    at Worker.worker.onmessage.message (http://localhost:3001/dist/index.mjs:767:7)
createNode @ nodes.js:69
nodes.forEach.node @ mutator.js:120
mutate @ mutator.js:120
worker.onmessage.message @ install.js:50
01:25:33.589 
```

The offending line, where it calls `createElement` instead of `createDocumentFragment`:
```
const node = namespace ? document.createElementNS(namespace, nodeName) : document.createElement(nodeName); // TODO(KB): Restore Properties
```

I also got an error `'HTMLElement' is not defined` at some point (this is inside vNext framework code, not 100% sure about the execution context). At that same spot, `Element` and `SVGElement` are defined however. I'm not sure if this tells you anything, so let me know if you need me to dig a little further :)

**Comment by fkleuver** [comment]
@kristoferbaxter Nice! I just tested it, the `DocumentFragment` is created and populated with cloned nodes. From that perspective things appear to be working.

The `querySelectorAll` API seems to be missing on `DocumentFragment`. We use a marker class `"au"` to indicate which elements have framework behavior on them, which the runtime then uses to retrieve them from the fragment via `.querySelectorAll(".au")`. I updated the checklist accordingly.

Let us know if we can do anything to help :)

**Comment by kristoferbaxter** [comment]
We just merged `DocumentFragement` support into master, complete with `ParentNode` mixin methods like `querySelectorAll`.

Give it a go, and let me know if it's working for you.

**Comment by fkleuver** [comment]
@kristoferbaxter Yep, basic interpolation binding is working! Awesome :)
I'll do some more extensive testing later this week.

By the way, could it be that `addEventListener` et al aren't working / implemented yet?

**Comment by kristoferbaxter** [comment]
`addEventListener` and ilk should be working, but if you have a sample repo with it failing let's create an issue for it and fix things up.

**Comment by fkleuver** [comment]
That sounds like a plan. The main issue at the moment (which is why I haven't done that yet) is `HTMLElement` not being defined in the global scope.
We use this class as an alternative DI registration key that users can inject the element instance with in their custom elements. Right now I need to remove that particular line every time after bundling.
For our purposes it really doesn't matter if it's just an alias to `Element`, it just needs to exist.
